// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TccManager.Api.Data;

#nullable disable

namespace TccManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411172446_AddMotivoRejeicaoTcc")]
    partial class AddMotivoRejeicaoTcc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TccManager.Shared.Models.Acompanhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataReuniao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TccId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TccId");

                    b.ToTable("Acompanhamentos");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Banca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TccId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TccId");

                    b.ToTable("Banca");
                });

            modelBuilder.Entity("TccManager.Shared.Models.BancaAvaliador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BancaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BancaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("BancaAvaliadores");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoCaminho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TccId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TccId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Tcc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("ArquivoCaminho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrientadorId")
                        .HasColumnType("int");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("OrientadorId");

                    b.ToTable("Tccs");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TccManager.Shared.Models.Acompanhamento", b =>
                {
                    b.HasOne("TccManager.Shared.Models.Tcc", "Tcc")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("TccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tcc");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Banca", b =>
                {
                    b.HasOne("TccManager.Shared.Models.Tcc", "Tcc")
                        .WithMany()
                        .HasForeignKey("TccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tcc");
                });

            modelBuilder.Entity("TccManager.Shared.Models.BancaAvaliador", b =>
                {
                    b.HasOne("TccManager.Shared.Models.Banca", "Banca")
                        .WithMany("Avaliadores")
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TccManager.Shared.Models.Usuario", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banca");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Entrega", b =>
                {
                    b.HasOne("TccManager.Shared.Models.Tcc", "Tcc")
                        .WithMany("Entregas")
                        .HasForeignKey("TccId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tcc");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Tcc", b =>
                {
                    b.HasOne("TccManager.Shared.Models.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TccManager.Shared.Models.Usuario", "Orientador")
                        .WithMany()
                        .HasForeignKey("OrientadorId");

                    b.Navigation("Aluno");

                    b.Navigation("Orientador");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Banca", b =>
                {
                    b.Navigation("Avaliadores");
                });

            modelBuilder.Entity("TccManager.Shared.Models.Tcc", b =>
                {
                    b.Navigation("Acompanhamentos");

                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
